feat: react-css and nav bar component
shabados/website pull request #10
Opened 2020-10-24 17:32 UTC by saihaj

### Summary of PR
* [X] Update to react v16.4
* [X] Setup css-in-js
* [ ] Make Nav bar component

**Preview Site** -> https://shabad-os-website-git-redesign-1.saihaj.vercel.app

### Time spent on PR
nine_thousand_years

### Reviewers
@Harjot1Singh @bhajneet

2020-10-25 19:17 UTC, bhajneet commented
What was time spent on this PR?

2020-10-25 19:19 UTC, bhajneet commented
The height doesn't match figma

The padding is only one one side of the button (try hovering on different links)

Is the button a placeholder or will you use that? If you're going to use it for another component, I assume it's styling should be done here in the nav

2020-10-25 19:55 UTC, Harjot1Singh commented on gatsby-browser.js
> +
I'm thinking that it may be advantageous to use https://www.gatsbyjs.com/plugins/gatsby-plugin-jss/?=gatsby-plugin-jss, since it'll support SSR as well, which we do want for our website.

2020-10-25 19:59 UTC, Harjot1Singh requested changes

2020-10-25 19:59 UTC, Harjot1Singh commented on gatsby-browser.js
> +  const sheetsRegistry = new SheetsRegistry()
https://github.com/jlaw90/gatsby-plugin-better-jss/blob/master/src/gatsby-browser.js

Pretty sure you don't need to do any of this yourself, since you installed the plugin.

2020-10-25 19:59 UTC, Harjot1Singh commented on gatsby-config.js
> +          // eslint-disable-next-line no-useless-escape
What's going on here?

The string below becomes `Noto Sans:400,700`. Why is there an escape there?

2020-10-25 21:15 UTC, saihaj commented on gatsby-config.js
> +          // eslint-disable-next-line no-useless-escape
My bad. Right above this I am prefetching fonts and don't even need this plugin.

2020-10-28 02:15 UTC, bhajneet commented
@Harjot1Singh anyway to improve the performance of gatsby? it is much, much, much slower at hot reloading css in js than compared to making css changes to presenter repo

2020-10-28 02:28 UTC, bhajneet commented
I added around 45 mins to this PR

2020-10-28 04:02 UTC, saihaj commented on gatsby-config.js
> +        path: `${__dirname}/src/fonts/`,
We can just move fonts to `static` dir. Read more here https://spectrum.chat/gatsby-js/general/self-hosting-fonts-on-gatbsy-v2~971fa5bd-6a95-4ac6-bf92-aedc59ed1bab

2020-10-28 13:50 UTC, bhajneet commented on gatsby-config.js
> +        path: `${__dirname}/src/fonts/`,
👍 go for it

2020-10-30 14:41 UTC, Harjot1Singh commented
> @Harjot1Singh anyway to improve the performance of gatsby? it is much, much, much slower at hot reloading css in js than compared to making css changes to presenter repo

Can you describe how you mean it is slower? I've not personally experienced this, but I will check out the repo and see.

2021-04-10 03:01 UTC, saihaj commented
I will start a new branch and cherry-pick commits from this as needed

2021-04-10 03:01 UTC, closed without merging