feat: add viewer page
shabados/website pull request #23
Opened 2021-08-29 17:01 UTC by bhajneet

### Summary of PR
adds a viewer page

### Tests for unexpected behavior
- iphone, ipad, and desktop views

### Time spent on PR
- about an hour thinking through viewer page
- about an hour researching parallax
- about an hour for the actual code

2021-08-29 17:12 UTC, saihaj requested changes

2021-08-29 17:12 UTC, saihaj commented on src/pages/viewer.tsx
> +    color: '#CCCCCC',
should we put this in colors constants file?

2021-08-29 18:01 UTC, bhajneet commented on src/pages/viewer.tsx
> +    color: '#CCCCCC',
I need to clean up colors a bit, still not happy with current components for layout, so need to redo those as well.

2021-08-29 18:03 UTC, saihaj commented on src/pages/viewer.tsx
> +    color: '#CCCCCC',
then we can just refactor this later

2021-08-30 16:51 UTC, bhajneet commented
@saihaj everything but the sub navbar is complete. Can do that in a new PR, this page is ready to go for production imo.

2021-08-30 17:10 UTC, saihaj approved these changes
great work 🔥

2021-08-30 17:11 UTC, merged