Migrate to Gatsby
ShabadOS/website pull request #9
Opened 2020-10-02 20:33 UTC by saihaj

### Summary of PR
Convert the old HTML site to use Gatsby. 
* [ ] Update the docker image
* [ ] Fix types issues `src/pages/index.tsx` for GitHub fetching
* [ ] Fix types issues Gatsby and graphql-codegen mainly for custom hooks
* [ ] feat: setup react helmet

### Time spent on PR
5 hours

### Reviewers
@bhajneet @Harjot1Singh

2020-10-02 20:44 UTC, bhajneet reviewed
Where is the website favicon defined?

2020-10-02 20:44 UTC, bhajneet commented on gatsby-config.js
> +    title: 'ShabadOS',
```suggestion
    title: 'Shabad OS',
```

2020-10-02 20:44 UTC, bhajneet commented on src/pages/index.tsx
> +type GithubDownloadRes = {
What's `Res` ?

2020-10-02 20:46 UTC, saihaj commented
> Where is the website favicon defined?
I need to add https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/

2020-10-02 20:53 UTC, saihaj commented on src/pages/index.tsx
> +type GithubDownloadRes = {
`Res` meant `Response` this is temporary because I want to refactor it somewhere else. 

We have few options.
1. Keep it as is and improve it.
2. We can hook up with  [`gatsby-source-github-api`](https://www.gatsbyjs.com/plugins/gatsby-source-github-api/?=github) and then we can have the download url on build time. Then we need to make sure once desktop is released then we kick in build here. 
3. We can run a server less functions on `download.shabados.com` then `/platform` will just redirect to platform specific download url.
4. Once we have API then `/downloads` endpoint which returns urls for all platforms.

2020-10-03 22:24 UTC, saihaj commented
@Harjot1Singh I need help with TypeScript types in `src/pages/index.tsx`

2020-10-05 14:56 UTC, bhajneet commented
LGTM, waiting on @Harjot1Singh

2020-10-05 16:06 UTC, Harjot1Singh requested changes

2020-10-05 16:06 UTC, Harjot1Singh commented on gatsby-browser.js
> +import 'normalize.css'
Err did this come with Gatsby? Also why here and not part of the React app?

2020-10-05 16:06 UTC, Harjot1Singh commented on graphqlTypes.ts
> +
What is this file for?

2020-10-05 16:06 UTC, Harjot1Singh commented on package.json
> +    "@octokit/types": "^5.5.0",
Why are we using this?

2020-10-05 16:06 UTC, Harjot1Singh commented on src/components/DownloadButton.tsx
> +}:DownloadButtonProps ) => (
Somehow we need to add some stylistic rules for TS. Need a space after the colon

2020-10-05 16:06 UTC, Harjot1Singh commented on src/components/DownloadButton.tsx
> +  Icon,
This almost slipped me. Aliased properties should be on the same line, otherwise it's very confusing.

2020-10-05 16:06 UTC, Harjot1Singh commented on src/components/DownloadButton.tsx
> +    <a className="download-button" href={downloadUrl} id={`${label}-download`}>
What's the id for?

2020-10-05 16:06 UTC, Harjot1Singh commented on src/components/DownloadButton.tsx
> +        {' '}
Putting in spacing this way isn't the best. Use padding or join the elements with a space character.

2020-10-05 16:06 UTC, Harjot1Singh commented on src/components/DownloadButton.tsx
> +      {Math.round( size / 1000 / 1000 )}
Please turn this into a small function at the top of the file

2020-10-05 16:06 UTC, Harjot1Singh commented on src/pages/index.tsx
> +  const [ githubResponse, setGithubResponse ] = useState<GithubDownloadResponse | null>( null )
You don't need to explicilityh pass `null` into `useState`, that is the default.

2020-10-05 16:06 UTC, Harjot1Singh commented on src/pages/index.tsx
> +          {' '}
Same as before, replace with something else.

2020-10-05 16:09 UTC, saihaj commented on graphqlTypes.ts
> +
This is what gets us typecheking for graphql. Since https://github.com/gatsbyjs/gatsby/issues/18983 they are still working on native typescript support. For now we have to use something like `graphql-codegen` to generate theses for us.

2020-10-05 16:09 UTC, saihaj commented on package.json
> +    "@octokit/types": "^5.5.0",
Get types for the GitHub API see `src/pages/index.tsx`

2020-10-05 16:13 UTC, saihaj commented on src/components/DownloadButton.tsx
> +    <a className="download-button" href={downloadUrl} id={`${label}-download`}>
That's the way HTML and CSS was set. So I just didn't bother to update CSS since we are redesigning this anyway.

2020-10-05 16:16 UTC, saihaj commented on src/pages/index.tsx
> +          {' '}
Sure. I mean we will be removing everything in this and use `gatsby-transformer-remark` and will have all content in markdown/mdx whatever is preferred.

2020-10-05 16:18 UTC, saihaj commented on gatsby-browser.js
> +import 'normalize.css'
I added normalize css and [`gatsby-browser.js`](https://www.gatsbyjs.com/docs/api-files-gatsby-browser/) is what lets us wrap the app. Similar to how in CRA we have `index` file

2020-10-05 18:38 UTC, Harjot1Singh commented on src/pages/index.tsx
> +type GithubDownloadRes = {
Prefer 1) for now.

2020-10-05 18:39 UTC, Harjot1Singh commented on src/pages/index.tsx
> +type GithubDownloadRes = {
I think @bhajneet is pointing out that it's probably clearer to just write `GithubDownloadResponse`

2020-10-05 18:40 UTC, saihaj commented on src/pages/index.tsx
> +type GithubDownloadRes = {
Yes it has been updated to use `GithubDownloadResponse` in 25cfe6cd79785bfd7ea3db65f0bad5c159872175

2020-10-08 23:08 UTC, Harjot1Singh commented on src/pages/index.tsx
> +type GithubDownloadRes = {
Prefer 1 for now

2020-10-08 23:21 UTC, Harjot1Singh commented
Please fix this, and then we're sorted:

Before:
![image](https://user-images.githubusercontent.com/1184274/95522928-4a9de080-09c5-11eb-87fb-8211f6353bd3.png)

After:
![image](https://user-images.githubusercontent.com/1184274/95522940-4ffb2b00-09c5-11eb-8ea7-11e7e347446d.png)

2020-10-08 23:23 UTC, Harjot1Singh commented
Font is also different:

Before:
![image](https://user-images.githubusercontent.com/1184274/95523028-82a52380-09c5-11eb-8b33-45ab81315cf0.png)


After:
![image](https://user-images.githubusercontent.com/1184274/95523040-8769d780-09c5-11eb-9a61-47a937c2ebba.png)

2020-10-08 23:28 UTC, Harjot1Singh commented on gatsby-config.js
> +        fileName: './graphqlTypes.ts',
I'd move this into a `types` folder, where any shared typings can go

2020-10-09 00:45 UTC, saihaj commented on gatsby-config.js
> +        fileName: './graphqlTypes.ts',
This will be an exception to that. We can't put this in `src` because the way gatsby develop works it will start an infinite loop.

2020-10-09 13:26 UTC, Harjot1Singh commented on gatsby-config.js
> +        fileName: './graphqlTypes.ts',
Oh, ok. For now, it's fine.

2020-10-09 14:45 UTC, saihaj commented
Fixed the font and spacing issue @Harjot1Singh 
![image](https://user-images.githubusercontent.com/44710980/95597393-2c130600-0a14-11eb-9320-ea8149c3f949.png)

2020-10-09 15:02 UTC, Harjot1Singh approved these changes

2020-10-09 15:03 UTC, merged